### ISSUE TITLE
Permission to deploy on R Studio cloud?

### ISSUE THREAD

**Issue by jrosen48** [gadenbuie/tweet-conf-dash#1] opened 2019-04-06 12:38 UTC
Hi, and thanks for a great app! I am trying to deploy a version of the app for a conference I'm at, #AERA19, via R Studio Cloud, but receive this message: *Sorry, you do not have access.* I tried to deploy other apps which received awards for the 1st Shiny Competition and was able; I left a comment on RStudio's blog asking about this, too (see [here](https://blog.rstudio.com/2019/04/05/first-shiny-contest-winners/). Thanks!

**Comment by gadenbuie** [comment] 2019-04-06 17:10
Hey @jrosen48, I thought I had set it up for this but apparently I missed something. I’m AFK this weekend but will fix it on Monday. Thanks for letting me know!

**Comment by gadenbuie** [comment] 2019-04-08 17:30
Hi @jrosen48, I followed up with RStudio today and the issue is that I created the project inside a workspace. The workspace is open to everyone though, so you can [join the workspace at this link](https://rstudio.cloud/spaces/12362/join?access_code=jAbWrXZKjNbs04icEflvjxDzidJdGSWQWs600uHv), at which point when you open the project you'll have a temporary copy that you should be able to save into your account.

You're going to run into another issue, though, which is that the app itself doesn't handle the tweet collecting directly. You'll need to set up a separate process for collecting tweets about the conference, I recommend using [rtweet](https://rtweet.info) but I also created a command line wrapper around rtweet that eliminates much of the boilerplate code for using rtweet to collect tweets, called [gathertweet](https://github.com/gadenbuie/gathertweet). The search terms that are used in the Twitter search need to be aligned with the [topic settings here](https://github.com/gadenbuie/tweet-conf-dash/blob/0317ac6e8f803c732380571037b5430acfea47cd/00_settings.R#L39-L50) and there are a number of other metadata settings to change as well in [00_settings.R](https://github.com/gadenbuie/tweet-conf-dash/blob/master/00_settings.R#L39-L50).

The reason this functionality is separated from the app code is because 1) collecting Twitter data requires API tokens and credentials that were out of scope of the app contest and 2) Shiny apps on shinyapps.io run on demand making the Shiny app itself a poor fit for repeated and long-term tweet gathering. I plan to write up the set-up process more fully soon.

**Comment by gadenbuie** [comment] 2019-04-09 16:55
I moved the project so that it's no longer necessary to join a workspace in order to clone it: https://rstudio.cloud/project/258314

**Closed as completed by gadenbuie** 2019-04-09 16:55 UTC
Labels: question :question:
